version: '3'

services:
  #wordpress
  wordpress:
    image: wordpress:latest
    links:
      - mysql
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./app:/var/www/html
      - ./htaccess_dev:/var/www/html/.htaccess
      - ./dev.ini:/usr/local/etc/php/conf.d/dev.ini
  #database mysql
  mysql:
    image: mysql:8.0.23
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    ports:
     - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
  #phpmyadmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
     - PMA_ARBITRARY=1
     - PMA_HOST=mysql
     - PMA_USER=root
     - PMA_PASSWORD=wordpress
    restart: always
    ports:
     - 8081:80
    volumes:
     - /sessions
#  mailhog:
#    image: mailhog/mailhog
#    ports:
#      - "1025:1025"
#      - "8025:8025"
